# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ex2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ex2
  pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
pod 'Moya', '~> 11.0'
   pod 'PromiseKit'

  target 'Ex2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ex2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
